import client from 'prom-client';

export const register = new client.Registry();
client.collectDefaultMetrics({ register }); // event loop lag, memory, GC, etc.

export const httpRequestDuration = new client.Histogram({
  name: 'http_request_duration_seconds',
  help: 'HTTP request duration in seconds',
  labelNames: ['method', 'route', 'status_code'],
  buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2.5],
  registers: [register],
});

export const cacheHitsTotal = new client.Counter({
  name: 'cache_hits_total',
  help: 'Redis cache hits on the redirect path',
  registers: [register],
});

export const cacheMissesTotal = new client.Counter({
  name: 'cache_misses_total',
  help: 'Redis cache misses on the redirect path',
  registers: [register],
});

// The actual proof that DB shielding works: every time this fires, a
// Postgres query was skipped entirely because the shortcode shield could
// guarantee the code didn't exist.
export const shortcodeShieldHitsTotal = new client.Counter({
  name: 'shortcode_shield_hits_total',
  help: 'Redirect requests that skipped Postgres entirely because the shortcode shield guaranteed the code does not exist',
  registers: [register],
});

export const snowflakeIdsGeneratedTotal = new client.Counter({
  name: 'snowflake_ids_generated_total',
  help: 'Total Snowflake IDs generated by this instance',
  registers: [register],
});

export const clickEventsProcessedTotal = new client.Counter({
  name: 'click_events_processed_total',
  help: 'Click events successfully processed by the worker',
  registers: [register],
});

export const clickEventsFailedTotal = new client.Counter({
  name: 'click_events_failed_total',
  help: 'Click events that failed processing and were routed to the dead-letter queue',
  registers: [register],
});

export const expirySweepDeactivatedTotal = new client.Counter({
  name: 'expiry_sweep_deactivated_total',
  help: 'Links deactivated by the daily expiry sweep cron job',
  registers: [register],
});

export const safeBrowsingChecksTotal = new client.Counter({
  name: 'safe_browsing_checks_total',
  help: 'URL safety checks against Google Safe Browsing, by result',
  labelNames: ['result'], // clean | flagged | error | skipped (not configured)
  registers: [register],
});

export const pageEnrichmentTotal = new client.Counter({
  name: 'page_enrichment_total',
  help: 'Background page metadata fetches (title/category/summary), by outcome',
  labelNames: ['result'], // success | timeout | blocked_status | non_html | ssrf_blocked | network_error
  registers: [register],
});
